### ISSUE TITLE
NCDstack not lazy loading when selecting on dimensions?

### ISSUE THREAD

**Issue by ashleysommer** [rafaqz/GeoData.jl#134]
I have a very large (200GB) NetCDF file with two variables (layers).

If I load the file using `NCDarray("myfile.nc")` then I can only access the first layer.

So instead I load using `NCDstack("myfile.nc")` this allows me to have access to both layers in the file.

However when selecting a layer, I immediately get an out-of-memory error:
```julia
stack = NCDstack("myfile.nc")
layer1 = stack[:layer1] #<<<- Out of memory error here
point = layer1[Lat(x), Lon(y)]
```

This also happens when I try to pre-select one specific lat/lon coordinate to limit the scope:
```julia
stack = NCDstack("myfile.nc")
point = stack[Lat(x), Lon(y)] #<<<- Out of memory error here
layer1 = point[:layer1]
```

Note, it works normally without error when using NCDarray instead of NCDstack:
```julia
array = NCDarray("myfile.nc")
point = array[Lat(x), Lon(y)]
# No errors, and data isn't loaded into memory yet (lazy-loaded)
```

Is this a bug? Or is this how NCDstack is supposed to work?

**Comment by ashleysommer** [comment]
I think I just found my answer in the docs:
https://rafaqz.github.io/GeoData.jl/stable/#Stack

>getindex on a AbstractGeoStack generally returns a memory backed standard GeoArray. geoarray[:somelayer] |> plot plots the layers array, while geoarray[:somelayer, Lon(1:100), Band(2)] |> plot will plot the subset without loading the whole array.

**Comment by ashleysommer** [comment]
Update,
Ok, I thought I had tried it, but looks like this is working now:
```
point = stack[:layer1, Lat(x), Lon(y)]
```
I swear I tried that earlier and it didn't work, but it is now.

**Comment by rafaqz** [comment]
Yeah, consider all this behaviour still up for debate. Its not clear to me yet where/how long to keep the array lazy.

If you have an alternative consistent set of behaviours that was better we could equally switch to it.

**Comment by ashleysommer** [comment]
Hi @rafaqz 

Most of my past experience is with xarray in Python.

In xarray, I can do it like this:

```python
    ds = xr.open_dataset("myfile.nc")
    layer1 = ds["layer1"]  # <- Select this layer, but don't load it into RAM
    point = layer1.sel(lat=x, lon=y) # <- Preselect this point, but don't load the data yet
    #point = point.load() # <- Can explicitly tell xarray to pull the data into RAM now
    data = point.values[:] # <- Or copy the data out without xarray pre-loading it
```

Of course I don't expect GeoData.jl and DimensionalData.jl to be a copy of xarray. 

I think my main point is that it was counter-intuitive for me that `NCDstack` will load the layer into RAM when selecting a layer with `l = stack[:layer1]` or even selecting a point `point = stack[Lat(x), Lon(y)]` while the same operation on NCDarray uses lazy loading. Though it is good that that can be found in the documentation if you look for it. But after learning that, it is further counter-intuitive to find that selecting a stack with a combination like `point = stack[:layer1, Lat(x), Lon(y)]` _does_ use lazy loading.

**Comment by rafaqz** [comment]
What happens in the last case is no using lazy loading either, its just directly loading the selection to memory without loading the whole array.

But I get your point - delaying the load as long as possible is important, `NCDstack[:key]` should return `NCDarray`. Loading a point with regular indexing will have to be to memory, be we should be able to use `view` to continue lazy loading. It's just a little tricky to implement given how `view` and DimentionalData.jl normally interact, and I haven't had time yet!

With the comparison to Xarray, its good to be clear that this is a side project for one person with a few contributors, with very occasional minor funding, and it's still less than a year since release. So don't expect the level of polish... But that also means this kind of help and feedback on anything are really useful and you can influence how it works quite a lot.

**Comment by ashleysommer** [comment]
I'm working in Environmental Informatics in a research organization, putting my feelers out to see whether we can start to replace some of our Python code with Julia, and any potential advantages that might bring. I understand this is a developing area, Julia is a young language with a relatively small and immature ecosystem.

I contribute to a lot of open source projects in Python, and I'm keen to help with that where possible in the Julia space. I'm still learning the ropes, but hopefully will eventually be able to make meaningful contributions to this project and others.

**Comment by rafaqz** [comment]
Oh interesting, we are in similar situation. I wrote this package partly because my ecology/agriculture research organization was slowly switching from R to Julia. Overall it's worked out well for us in terms of the tools we have now that you could never write in R or Python, but it was a lot of work when you also have to write tools like this to support the other things you want to do... It should be a little easier to make the switch now than it was a few years ago.

**Comment by maxfreu** [comment]
> Yeah, consider all this behaviour still up for debate.

Hmm similar to what you suggested, I think it would be easiest to make a clear distinction between view and getindex. I would expect getindex to be eager and view to be lazy, being converted to getindex calls upon collect, array creation or anything not supporting views. So if the user wants lazy calls he has to state it explicitly using `@views`. But probably I'm missing on a ton of subtleties...

**Comment by rafaqz** [comment]
Yeah, thats how it should work. We just need another internal wrapper `<: AbstractArray` to wrap with `view`. The view cant be the outside wrapper, or you lose dim/selector indexing.
