### ISSUE TITLE
Write GDALarray with X-Y coordiates

### ISSUE THREAD

**Issue by mauro3** [rafaqz/GeoData.jl#140]
Currently I get:
```
julia> write("/tmp/t.tif", GDALarray, ar)
ERROR: Array must have Lat and Lon dims
...
```
As my `ar` is in a projected coordinate system it has X-Y dims:
```
julia> dims(ar)
(X (type X): Int32[-1800000, -1799500, …, -960500, -960000] (Sampled: Ordered Regular Intervals), Y (type Y): Int32[-880000, -879500, …, 139500, 140000] (Sampled: Ordered Regular Intervals))
```

Is this a missing feature or am I missing something?

**Comment by rafaqz** [comment]
Yes this needs thought. It should probably permute by `XDim` and `Ydim` to be more generic. But Lat and Lon are used in the sense that you are aligned to lat/lon grid, not that they actually hold lat/lon values. You can always use `mappedcrs=EPSG(4326)` to make it behave like lat/lon in practice so its kind of blurry anyway.

And maybe thats confusing, this is all up for debate. I was wondering if we should just use X and Y by default and ditch Lat and Lon.

**Comment by mauro3** [comment]
> But Lat and Lon are used in the sense that you are aligned to lat/lon grid, not that they actually hold lat/lon values.

Do you mean that I should use `Lat` `Lon` for all spatial data? And `X`, `Y` are more though for DimensionalData arrays, i.e. non-geo arrays?  Can I use `Lat` `Lon` and set `mappedcrs=EPSG(something-not-lat-lon)`?

I guess you could call them `Easting` and `Westing` to be more generic (which could also include lat-lon) and to distinguish from non-geo `X`, `Y`.

**Comment by rafaqz** [comment]
Yeah, maybe.

Netcdf  mostly calls them lat and lon, because they map the axis vector to lat and lon from the projection, so I went with `Lat` and `Lon` here. But yes it's more like `Easting`/`Northing`.

We recently have `GeoXDim/GeoYDim/GeoZDim` that are used in plots, and you can inherit dims from. I really should make GDAL use those for permutation. They basically mean that the dimensions are explicitly geospatial data, and plots of these dimensions are always heatmaps - as opposed some other variable you want to scatter plot - which is what DD dimensions do by default.

But I've been thinking that we could even drop this distinction and just assume `X/Y/Z` dims in a `AbstractGeoArray` are always spatial, and plotted as heatmaps. It would be simpler. Then we could just use `X` for `Lon` and `Y` for `Lat`, and delete a bunch of unnecessary code.


When you encounter any of these things its good to keep in mind both that I'm an ecologist/biogeograper, not a real GIS guy. Being the package author means only that I can practically code this kind of thing fairly easily, not that I know what I'm doing technically, especially with the older code. The design space is also pretty big and unclearly bounded. I think lot of editing needs to happen as things get clearer - so input like this is really useful.

**Comment by rafaqz** [comment]
> Can I use Lat Lon and set mappedcrs=EPSG(something-not-lat-lon)?

Yes, it can be anything in any projection format from GeoFormatTypes.jl. So yeah they are not really Lat/Lon :)

**Comment by mauro3** [comment]
> But I've been thinking that we could even drop this distinction and just assume X/Y/Z dims in a AbstractGeoArray are always spatial, and plotted as heatmaps. It would be simpler. Then we could just use X for Lon and Y for Lat, and delete a bunch of unnecessary code.

This sounds good.

> so input like this is really useful.

I'm not a GIS guy either ;-)

**Comment by rafaqz** [comment]
Well I guess we'll all muddle through this together then! I'll consider the switch to `X/Y/Z`. Maybe we can do:

```julia
const Lon = X
const Lat = Y
```

To soften the blow a little, although its not really backwards compat.

**Comment by rafaqz** [comment]
@mauro3 I invited you as a collaborator here, it would be good to be able to flag you for PR reviews if you have time - so I make less bad decisions like this in future :/

**Comment by mauro3** [comment]
Thanks!  I hope I can be of assistance, just ping me.  (But note, I'm a bit short on time, as I'm sure you are too.)
