### ISSUE TITLE
replace_missing should just do nothing if missingval is allready missing

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/GeoData.jl#63]
Currently this throws:

```julia
MethodError: Cannot `convert` an object of type Missing to an object of type Float64
```

Which makes no sense

**Comment by ayushpatnaikgit** [comment]
Hi, I have the following Raster: 
```
julia> dc
84×155×1×123 Raster{Float32,4} unnamed with dimensions: 
  X Mapped Float64[72.7250001018, 72.72916676850001, …, 73.0666667712, 73.0708334379] ForwardOrdered Explicit Intervals crs: EPSG mappedcrs: EPSG,
  Y Mapped Float64[19.495832889299994, 19.491666222599996, …, 18.858332884200003, 18.8541662175] ReverseOrdered Explicit Intervals crs: EPSG mappedcrs: EPSG,
  Band Categorical Int64[1] ReverseOrdered,
  Ti Sampled Int64[201204, 201205, …, 202205, 202206] ForwardOrdered Irregular Points
with missingval: missing
```

I want to do something like: 
```
dc[1,1,1,1] = missing
```
I wish to do this because the list of missing observations is provided in a separate file, and I have to manually mark the missing observations. 

But get the error that you have mentioned above. 
Any suggestions? 

I feel if `missingval` is `missing`, the Raster should automatically be `Union{Missing, something}` 

Apologies, if this issue wasn't the most suitable place to ask this question.

**Comment by rafaqz** [comment]
Thanks I just forgot about this!

**Comment by ayushpatnaikgit** [comment]
Thanks, Rafael, 
I'll open a new issue and share the .nc file.
